### ISSUE TITLE
Do not package the mongodb data dir

### ISSUE THREAD

**Issue by ChALkeR** [infolis/mongoose-jsonld-express#1]
_Disclaimer: I do not use the package, this was found during automated npm packages downloading._

Your current package size is 296 KiB packed, **289 MiB** unpacked. 289 MiB of that are inside the `data/mongodb` dir. I think that this probably got packed to the release by mistake.

You could add that dir to the `.gitignore` and/or `.npmignore`.

**Comment by kba** [comment]
The package was obsolete anyway. I unpublished it. Thanks for letting us know.
